DoubleJONY/KDJ-algorithm-challenge

- minsoo/.gitignore
- minsoo/hash/best_album.py
- minsoo/hash/disguise.py
- minsoo/hash/phone_book.py
- minsoo/hash/who_did_not_complete_the_race.py
who_did_not_complete_the_race.py
phone_book.py
disguise.py
best_album.py
> hash added

- minsoo/.gitignore
- minsoo/hash/best_album.py
- minsoo/hash/disguise.py
- minsoo/hash/phone_book.py
- minsoo/hash/who_did_not_complete_the_race.py
- minsoo/stack_queue/deployment.py
- minsoo/stack_queue/printer.py
- minsoo/stack_queue/stock_price.py
- minsoo/stack_queue/trapping_rain_water.py
- minsoo/stack_queue/truck_passing_bridge.py
+ .gitignore update
+ similar variant of stock price from [leetcode](https://leetcode.com/problems/trapping-rain-water/) added
+ new line is added at the end of each files
> stack/queue added & miscellaneous

- heoh/programmers-42583.py
무ㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜ지ㅣㅣㅣㅣㅣㅣㅣㅣㅣㅣㅣ성 풀이
무ㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜ지ㅣㅣㅣㅣㅣㅣㅣㅣㅣㅣㅣ 길다
혹시 읽으시려면, `def simulate(self):` 만 읽으시면 됩니다.
그래도 시간 복잡도 손해는 없음
> 다리를 지나는 트럭: 무지성 풀이

- heoh/programmers-42583-2.py
로직은 #12 과 같음.
짧아서 이게 더 보기 쉬운가??
> 다리를 지나는 트럭: 적당히 추상화한 풀이

- kujin-CSharp/Heap/heap_p2.cs
테스트 케이스는 죄다 통과하는데 실제로 들어가면 2번 3번 15번 17번이 틀림
근데 풀이에 있는 코드 돌리면 무한루프 걸리는거 실화?
> 디스크 컨트롤러 왜 틀리는지 모르곘네

- kujin-CSharp/Sort/Sort_1.cs
- kujin-CSharp/Sort/Sort_2.cs
- kujin-CSharp/Sort/Sort_3.cs
> SORT CSHARP

- minsoo/greedy/connecting_islands.py
- minsoo/greedy/gym_suit.cc
- minsoo/greedy/gym_suit.py
- minsoo/greedy/joystick.py
- minsoo/greedy/largest_number.cc
- minsoo/greedy/largest_number.py
- minsoo/greedy/lifeboat.py
- minsoo/greedy/speed_camera.py
```
gym_suit.py
테스트 1 〉 | 통과 (0.01ms, 10MB)
테스트 2 〉 | 통과 (0.01ms, 10.2MB)
테스트 3 〉 | 통과 (0.01ms, 10.2MB)
테스트 4 〉 | 통과 (0.01ms, 10.2MB)
테스트 5 〉 | 통과 (0.01ms, 10.4MB)
테스트 6 〉 | 통과 (0.01ms, 10MB)
테스트 7 〉 | 통과 (0.01ms, 10.1MB)
테스트 8 〉 | 통과 (0.01ms, 10.2MB)
테스트 9 〉 | 통과 (0.01ms, 10.1MB)
테스트 10 〉 | 통과 (0.01ms, 10.2MB)
테스트 11 〉 | 통과 (0.01ms, 10.1MB)
테스트 12 〉 | 통과 (0.00ms, 10.2MB)
테스트 13 〉 | 통과 (0.01ms, 10.1MB)
테스트 14 〉 | 통과 (0.01ms, 10.2MB)
테스트 15 〉 | 통과 (0.01ms, 10.2MB)
테스트 16 〉 | 통과 (0.01ms, 10.2MB)
테스트 17 〉 | 통과 (0.01ms, 10.2MB)
테스트 18 〉 | 통과 (0.01ms, 10.2MB)
테스트 19 〉 | 통과 (0.01ms, 10.2MB)
테스트 20 〉 | 통과 (0.01ms, 10.1MB)
```
```
gym_suit.cc
테스트 1 〉 | 통과 (0.01ms, 3.93MB)
테스트 2 〉 | 통과 (0.01ms, 3.73MB)
테스트 3 〉 | 통과 (0.01ms, 4.3MB)
테스트 4 〉 | 통과 (0.01ms, 3.95MB)
테스트 5 〉 | 통과 (0.01ms, 3.91MB)
테스트 6 〉 …
```
> greedy added

- heoh/boj-12100.py
네 방향으로 미는걸 만들면 실수할까봐
성능을 포기하고 회전을 넣음
이거 네 방향 한 가지 함수로 짜는법 좀;
> 2048 (Easy)

- minsoo/baekjoon/14500.cc
- minsoo/baekjoon/14500_timeout.py
- minsoo/baekjoon/14501.py
- minsoo/baekjoon/14502.py
> baekjoon week 3

- jony-java/src/test/java/com/doublejony/backjun/BackjunJavaTemplates.txt
- jony-java/src/test/java/com/doublejony/backjun/samsungSWTest/BJ14499.java
- jony-java/src/test/java/com/doublejony/backjun/samsungSWTest/BJ14499.txt
- jony-java/src/test/java/com/doublejony/backjun/samsungSWTest/BJ14500.java
- jony-java/src/test/java/com/doublejony/backjun/samsungSWTest/BJ14501.java
- jony-java/src/test/java/com/doublejony/backjun/samsungSWTest/BJ14501.txt
- jony-java/src/test/java/com/doublejony/backjun/samsungSWTest/BJ14502.java
- jony-java/src/test/java/com/doublejony/backjun/samsungSWTest/BJ14502.txt
- jony-java/src/test/java/com/doublejony/playground/DayDic.java
- jony-java/src/test/java/com/doublejony/playground/DayPrinter.java
- jony-java/src/test/java/com/doublejony/playground/Median.java
- jony-java/src/test/java/com/doublejony/playground/PlayGround.java
- jony-java/src/test/java/com/doublejony/programmers/practice/kakao2018/TressureMap.java
> 14499 - 주사위 굴리기

- heoh/leetcode-1622.cpp
- heoh/leetcode-1622.py
- `Fancy Sequence: TLE`: 사실상 시간 초과 로직인데, `C++`에서는 가끔 운이 좋게 Accept 됨;;
- `Fancy Sequence: O(Log M) 풀이`: 결국 GG치고 인터넷에 mod 나눗셈 방법을 찾아서 갖다 씀...
> 1622. Fancy Sequence

- heoh/leetcode-843.py
`wordlist` 중 어떤 단어를 물어볼지 우선순위를 결정하는 방법을 모르겠음.
이상한 식으로 찍어서 통과는 됐지만, 내가 구현한 로직 자체가 운빨인듯
> 843. Guess the Word

- rhino/src/com/rhino/leetcode/Hard00843_Guess_the_world.java
- rhino/src/com/rhino/leetcode/Hard1622_Facny_Sequence.java
Fancy Sequence & Guess Word
Fancy Seq 의 경우 수학문제였으며,차후에 다시  풀어봐야 함.
Guess Word의 경우, 대화형 문제로, seq하게 get 하는 방식도 있지만, 그냥 rand를 돌림.
(그렇다고 효율이 좋아지는 건 아님.)
대화형으로 develop해 가서 결국에는 100% 확률로 matching 되는 문제가 아니기에, 이정도에서 멈추기로 자체 결정함.
> Rhino - fancy sequence & Guess word

- owen/leetcode/P1622_FancySequence.py
- owen/samsung/resignation.py
> resignation

- .gitignore
- jony-java/src/test/java/com/doublejony/common/AssertResolveCustom.java
- jony-java/src/test/java/com/doublejony/leetcode/Leet2074.java
- jony-java/src/test/java/com/doublejony/leetcode/Leet329.java
- jony-java/src/test/java/com/doublejony/leetcode/Leet61.java
- jony-java/src/test/java/com/doublejony/leetcode/Leet86.java
- jony-java/src/test/java/com/doublejony/leetcode/entities/ListNode.java
> leetcode 3주차

- kujin-CSharp/Leet/86PartitionList.cs
> PartitionList

- kujin-CSharp/Leet/M61RotateList.cs
> M61RotateList

- heoh/leetcode-956.py
> 956. Tallest Billboard

- heoh/leetcode-81.py
O(N) 풀이: 62 ms
느린 O(Log(N)) 풀이: 60 ms
이게.. 풀이냐..
> 81. Search in Rotated Sorted Array II

- minsoo/baekjoon/15685.py
[72 ms](https://www.acmicpc.net/source/42450855)
> baekjoon week 10

- minsoo/baekjoon/15686.py
> baekjoon week 11

- minsoo/baekjoon/5373.py
Python 3: 1948 ms
PyPy: 1012 ms
> baekjoon week 12

- minsoo/baekjoon/16234.py
- minsoo/baekjoon/16235.py
- 인구이동
Python 3: TLE
PyPy: 1808 ms
- 나무 재테크
Python 3: TLE
PyPy: 684 ms
> baekjoon week 13

- minsoo/baekjoon/17143.py
- minsoo/baekjoon/17144.py
미세먼지 안녕!
- Python 3 TLE
- PyPy3 448 ms
낚시왕
- Python 3 2192 ms
- PyPy3 1056ms
> baekjoon week 16

- minsoo/baekjoon/17140.py
> baekjoon week 17

- heoh/boj-17140.py
> 이차원 배열과 연산

- minsoo/baekjoon/17142_alt.py
Python 3 - 1152 ms
PyPy3 - 276 ms
> baekjoon week 18

- README.md
- minsoo/baekjoon/17779.py
> readme update

- minsoo/baekjoon/17837.py
> baekjoon week 20

- minsoo/baekjoon/19236.py
> baekjoon week 24

- minsoo/baekjoon/19237.py
Python 3 - 524 ms
PyPy3 - 304 ms
> baekjoon week 25

- minsoo/baekjoon/20055.py
> baekjoon week 27

- heoh/boj-20055.py
- Python 3: 시간 초과
- PyPy3: 116368 KB, 840 ms
> 컨베이어 벨트 위의 로봇

- minsoo/baekjoon/20056.py
Python 3 - 724 ms
PyPy3 - 372 ms
> baekjoon week 28

- minsoo/baekjoon/20057.py
Python 3 - 2392 ms
PyPy3 - 300 ms
> baekjoon week 29

- heoh/boj-20057.py
- Python 3: 39740 KB, 1380 ms
- PyPy3: 117608 KB, 240 ms
> 마법사 상어와 토네이도

- jony-java/src/test/java/com/doublejony/baekjoon/Main.java
- jony-java/src/test/java/com/doublejony/baekjoon/samsungSWTest/BJ20058.java
> 마법사 상어와 파이어스톰

- minsoo/baekjoon/21608.py
Python 3 - 124 ms
PyPy3 - 232 ms
> baekjoon week 31

- kujin-CSharp/Backjoon/BOJ21610/main.rs
> 물 복사 버그 비바라기

- minsoo/baekjoon/21611.py
Python 3 - 232 ms
PyPy3 - 180 ms
> baekjoon week 34

- heoh/boj-21611.py
- Python 3: 30852 KB, 384 ms
- PyPy3: 118136 KB, 228 ms
> 마법사 상어와 블리자드

- minsoo/baekjoon/23288.py
Python 3 - 1128 ms
PyPy3 - 420 ms
> baekjoon week 35

- minsoo/baekjoon/23289.py
- minsoo/baekjoon/tester.py
| 언어 | 메모리 | 시간 |
| - | - | - |
| Python 3 | 32864 KB | 772 ms |
| PyPy3 | 199852 KB | 3180 ms |
`python tester.py <name-of-solver-script>`
- solver와 tester는 같은 디렉토리에 위치해야 함.
- solver의 이름은 문제번호로 시작하여 그 끝을 숫자가 아닌 문자로 구분할 수 있어야 함.
ex) 23289_my_elegant_answer.py
> baekjoon week 36 + tester

- minsoo/baekjoon/23290.py
- minsoo/baekjoon/tester.py
언어 | 메모리 | 시간
-- | -- | --
Python 3 | 59316 KB | 4884 ms
PyPy3 | 200780 KB | 1136 ms
`tester.py`의 OS 의존적인 요소들 변경
- os.path.join -> urllib.parse.urljoin
- split("/")[-1] -> os.path.basename
사실 윈도우에서 테스트해보진 않음...
> baekjoon week 37 + tester 호환성 개선

- heoh/boj-23290.py
- List 버전
- Python 3: 177756 KB, 3980 ms
- PyPy3: 347784 KB, 2472 ms
- Counter 버전
- Python 3: 34368 KB, 76 ms
- PyPy3: 117492 KB, 200 ms
> 마법사 상어와 복제

- minsoo/baekjoon/23291.py
언어 | 메모리 | 시간
-- | -- | --
Python 3 | 30840 KB | 80 ms
> baekjoon week 38

- minsoo/leetcode/print_in_order.py
-- | -- | --
Python3 | 53 ms | 14.4 MB
> leetcode week 8

- heoh/heoh/leetcode-1114.cpp
> Print in Order

- heoh/leetcode-2207.py
> Maximize Number of Subsequences in a String

- minsoo/leetcode/maximize_number_of_subsequences_in_a_string.java
- minsoo/leetcode/maximize_number_of_subsequences_in_a_string.py
-- | -- | --
Python3 | 156 ms | 14.9 MB
Java | 10 ms | 42.6 MB
> leetcode week 9

- minsoo/leetcode/count_the_hidden_sequences.py
-- | -- | --
Python3 | 1345 ms | 28.5 MB
> leetcode week 11

- minsoo/leetcode/strange_printer.py
-- | -- | --
Python3 | 703 ms | 13.9 MB
> leetcode week 12

- heoh/leetcode-1442.py
> Count Triplets That Can Form Two Arrays of Equal XOR

- minsoo/leetcode/count_triplets_that_can_form_two_arrays_of_equal_xor.py
- minsoo/leetcode/count_triplets_that_can_form_two_arrays_of_equal_xor_dp.py
Method | Language | Runtime | Memory
-- | -- | -- | --
DP | Python3 | 3620 ms | 15.8 MB
Prefix Sum? | Python3 | 40 ms | 13.9 MB
> leetcode week 13

- kujin-CSharp/Leet/1442Leet.cpp
> leetcode1442

- minsoo/leetcode/remove_all_adjacent_duplicates_in_string_ii.py
- minsoo/leetcode/remove_all_adjacent_duplicates_in_string_ii_efficient.py
-- | -- | --
Python3 | 5495 ms | 25.4 MB
Python3 | 103 ms | 18.6 MB
> leetcode week 14

- heoh/leetcode-1209.py
> Remove All Adjacent Duplicates in String II

- minsoo/leetcode/word_ladder_ii.py
-- | -- | --
Python3 | 38 ms | 14.8 MB
> leetcode week 15

- heoh/leetcode-126.py
> Word Ladder II

- heoh/leetcode-236.py
Runtime: 82 ms
Memory Usage: 26.6 MB
> Lowest Common Ancestor of a Binary Tree
